require 'fastlane/action'
require_relative '../helper/shory_helper'

module Fastlane
  module Actions
    class ShoryIosAppPathAction < Action
      def self.run(params)
        app_path = File.join(params[:app_path_prefix], other_action.shory_ios_app_filename(
          app_name: params[:app_name],
          app_environment: params[:app_environment], 
          xcodeproj_path: params[:xcodeproj_path],
          target: params[:target]
        ))
        ENV["SHORY_IOS_APP_PATH"] = app_path
        UI.success("SHORY_IOS_APP_PATH: #{app_path}")
        return app_path
      end

      def self.description
        "Generate an app file path for the iOS App."
      end

      def self.authors
        ['Shory Technologies LLC']
      end

      def self.return_value
        [
          ["SHORY_IOS_APP_PATH", "The path to the built iOS App."]
        ]
      end

      def self.details
        "The filename will be composed of `app_path_prefix` and filename generated by the `shory_ios_app_filename` action."
      end

      def self.available_options
        [
          Helper::ShoryHelper.ios_app_path_prefix,
          Helper::ShoryHelper.app_name,
          Helper::ShoryHelper.app_environment,
          Helper::ShoryHelper.xcodeproj_path,
          Helper::ShoryHelper.ios_target
        ]
      end

      def self.is_supported?(platform)
        platform == :ios
      end
    end
  end
end
