require 'fastlane/action'
require_relative '../helper/shory_helper'

module Fastlane
  module Actions
    class ShoryAndroidGenerateAppFilenameAction < Action
      def self.run(params)
        version = other_action.shory_android_get_version_number(gradle_path: params[:gradle_path])
        build = other_action.shory_android_get_build_number(gradle_path: params[:gradle_path])
        build_extension = Helper::ShoryHelper.gradle_extension_for(params[:build_task])
        app_name = "#{params[:app_name]}_#{params[:app_environment]}_#{version}_#{build}_#{other_action.shory_last_commit_message()}.#{build_extension}"
        ENV["SHORY_ANDROID_APP_FILENAME"] = app_name
        UI.success("SHORY_ANDROID_APP_FILENAME: #{app_name}")
        return app_name
      end

      def self.description
        "Generate an app filename for the Android app."
      end

      def self.authors
        ['Shory Technologies LLC']
      end

      def self.return_value
        [
          ["SHORY_ANDROID_APP_FILENAME", "App filename generated by the action."]
        ]
      end

      def self.details
        "The filename will follow this logic:
<app_name>_<app_environment>_<version>_<build>_<last_commit_message>.aab
The version and build numbers are fetched from the Gradle build file.
Uses `shory_last_commit_message` action to get the last commit message."
      end

      def self.available_options
        [
          Helper::ShoryHelper.app_name,
          Helper::ShoryHelper.app_environment,
          Helper::ShoryHelper.gradle_path,
          Helper::ShoryHelper.android_build_task
        ]
      end

      def self.is_supported?(platform)
        platform == :android
      end
    end
  end
end
