require 'fastlane/action'
require_relative '../helper/shory_helper'

module Fastlane
  module Actions
    class ShoryAndroidGenerateAppPathAction < Action
      def self.run(params)
        app_path = File.join(params[:app_path_prefix], other_action.shory_android_generate_app_filename(
          app_name: params[:app_name],
          app_environment: params[:app_environment], 
          gradle_path: params[:gradle_path],
          build_task: params[:build_task]
        ))
        ENV["SHORY_ANDROID_APP_PATH"] = app_path
        UI.success("SHORY_ANDROID_APP_PATH: #{app_path}")
        return app_path
      end

      def self.description
        "Generate an app file path for the Android app."
      end

      def self.authors
        ['Shory Technologies LLC']
      end

      def self.return_value
        [
          ["SHORY_ANDROID_APP_PATH", "Path generated by the action."]
        ]
      end

      def self.details
        "The filename will be composed of `app_path_prefix` and filename generated by the `shory_android_get_app_filename` action."
      end

      def self.available_options
        [
          Helper::ShoryHelper.android_app_path_prefix,
          Helper::ShoryHelper.app_name,
          Helper::ShoryHelper.app_environment,
          Helper::ShoryHelper.gradle_path,
          Helper::ShoryHelper.android_build_task
        ]
      end

      def self.is_supported?(platform)
        platform == :android
      end
    end
  end
end
