require 'fastlane/action'
require_relative '../helper/shory_helper'

module Fastlane
  module Actions
    class ShoryIosAppFilenameAction < Action
      def self.run(params)
        version = other_action.get_version_number(xcodeproj: params[:xcodeproj_path], target: params[:target])
        build = other_action.get_build_number(xcodeproj: params[:xcodeproj_path])
        app_name = "#{params[:app_name]}_#{params[:app_environment]}_#{version}_#{build}_#{other_action.shory_last_commit_message()}.ipa"
        ENV["SHORY_IOS_APP_FILENAME"] = app_name
        UI.success("SHORY_IOS_APP_FILENAME: #{app_name}")
        return app_name
      end

      def self.description
        "Generate an app filename for the iOS App."
      end

      def self.authors
        ['Shory Technologies LLC']
      end

      def self.return_value
        [
          ["SHORY_IOS_APP_FILENAME", "App filename generated by the action"]
        ]
      end

      def self.details
        "The filename will follow this logic:
<app_name>_<app_environment>_<version>_<build>_<last_commit_message>.ipa
The version and build numbers are fetched from the Xcode project.
Uses `shory_last_commit_message` action to get the last commit message."
      end

      def self.available_options
        [
          Helper::ShoryHelper.app_name,
          Helper::ShoryHelper.app_environment,
          Helper::ShoryHelper.xcodeproj_path,
          Helper::ShoryHelper.ios_target,
        ]
      end

      def self.is_supported?(platform)
        platform == :ios
      end
    end
  end
end
