export const globalUtils: Record<string, string> = {
	'nj-primary-button-bg': 'bg-brand-500',
	'nj-secondary-button-bg': 'text-white',
	'nj-bg-brand': 'bg-brand-500',
	'nj-border-brand': 'border-brand-500',
	'nj-bg-brand-pressed': 'bg-brand-700',
	'nj-border-brand-pressed': 'border-brand-700',
	'nj-radio-button-selected': 'border-brand-500',
	'nj-radio-button': 'border-gray-500',
	'nj-radio-content': 'gap-3',
	'nj-radio-card-item-container-font-family': 'font-main-bold',
	'nj-radio-label-font-family': 'font-main-semibold',
	'nj-radio-label-font-size': 'text-title',
	'nj-radio-label-horizontal-padding': 'px-2',
	'nj-radio-icon': 'w-5 h-5',
	'nj-otp-container': 'gap-4',
	'nj-otp-input-wrapper': 'h-17 w-21 justify-center items-center',
	'nj-otp-input': 'font-main-bold text-h1 text-gray-900',
	'nj-otp-input-disabled': 'bg-gray-400',
	'nj-otp-input-disabled-text-color': 'text-gray-600',
	'nj-border-radius': 'rounded-xl',
	'nj-bg-secondary': 'bg-white',
	'nj-border-secondary': 'border-brand-500',
	'nj-border-secondary-pressed': 'border-brand-100',
	'nj-text-brand-pressed': 'text-white',
	'nj-text-brand': 'text-white',
	'nj-text-button-text': 'text-secondary-900',
	'nj-social-button-border-radius': 'rounded-xl',
	'nj-social-button-border': 'border-gray-300',
	'nj-social-button-text': 'text-dark-1',
	'nj-dropdown-text': 'text-gray-900',
	'nj-primary-button-text': 'text-white',
	'nj-primary-button-text-font': 'font-main-bold',
	'nj-secondary-button-text': 'text-brand-500',
	'nj-button-spinner-bg-primary': 'bg-brand-700',
	'nj-button-spinner-bg-secondary': 'bg-dark-1',
	'nj-text-input-font': 'font-main-regular',
	'nj-text-input-font-size': 'text-paragraph',
	'nj-text-input-font-size-small': 'text-caption1',
	'nj-text-input-font-size-large': 'text-title',
	'nj-text-input-font-color': 'text-gray-600',
	'nj-text-input-line-height': 'leading-relaxed',
	'nj-text-input-prefix-align-items': 'items-center',
	'nj-text-input-container-padding': 'px-5 py-3',
	'nj-text-input-container-padding-small': 'px-5 py-1',
	'nj-text-input-container-padding-large': 'px-5 py-4',
	'nj-text-input-container-border-radius': 'rounded-2.5',
	'nj-text-input-container-error-bg': 'bg-white',
	'nj-text-input-container-error-border-color': 'border-red-400',
	'nj-text-input-container-disabled-border': 'border-none',
	'nj-text-input-container-disabled-border-color': 'border-transparent',
	'nj-text-input-container-disabled-bg': 'bg-gray-400',
	'nj-text-input-container-bg': 'bg-white',
	'nj-text-input-container-search-bg': 'bg-gray-100',
	'nj-text-input-container-search-border-width': 'border-0',
	'nj-text-input-prefix-default-color': 'text-gray-500',
	'nj-text-area-container-height': 'h-50',
	'nj-text-area-container-bg': 'bg-white',
	'nj-text-area-container-padding': 'px-5 py-3',
	'nj-text-area-container-border-radius': 'rounded-2.5',
	'nj-text-area-container-border-width': 'border',
	'nj-text-area-container-border-color': 'border-gray-600',
	'nj-text-area-container-error-bg': 'bg-white',
	'nj-text-area-font': 'font-main-regular',
	'nj-text-area-line-height': 'leading-relaxed',
	'nj-text-area-letter-spacing': 'tracking-normal',
	'nj-text-area-align-items': 'items-start',
	'nj-toast-success-bg-color': 'bg-green-50',
	'nj-toast-success-text-color': 'text-green-500',
	'nj-toast-warning-bg-color': 'bg-yellow-50',
	'nj-toast-warning-text-color': 'text-yellow-500',
	'nj-toast-error-bg-color': 'bg-red-50',
	'nj-toast-error-text-color': 'text-red-500',
	'nj-toast-info-bg-color': 'bg-blue-50',
	'nj-toast-info-text-color': 'text-blue-500',
	'nj-error-text-font': 'font-main-medium',
	'nj-error-text-font-color': 'text-red-400',
	'nj-error-text-font-size': 'text-paragraph',
	'nj-error-icon-display': 'block',
	'nj-error-container-width': 'w-full',
	'nj-error-container-bg': 'bg-red-100',
	'nj-error-container-border-radius': 'rounded-md',
	'nj-error-container-padding-horizontal': 'px-3',
	'nj-error-container-padding-vertical': 'py-2',
	'nj-error-container-margin-top': 'mt-2',
	'nj-error-container-gap': 'gap-2',
	'nj-error-container-flex': 'flex',
	'nj-error-container-align-items': 'items-center',
	'nj-text-field-placeholder-color': 'text-gray-500',
	'nj-otp-cell-border-size': 'border-2',
	'nj-otp-cell-border-color': 'border-red-400',
	'nj-otp-positive-cell-border-color': 'border-green-500',
	'nj-button-text-font': 'font-main-bold',
	'nj-dropdown-container-bg': 'bg-white',
	'nj-dropdown-menu-label-text-font': 'font-main-regular',
	'nj-dropdown-menu-label-text-color': 'text-dark-6',
	'nj-dropdown-menu-label-text-size': 'text-caption1',
	'nj-dropdown-menu-label-height': 'h-5',
	'nj-dropdown-menu-icon-color': 'text-dark-7',
	'nj-dropdown-menu-container-gap': 'gap-1',
	'nj-dropdown-bottom-sheet-title-font': 'font-main-bold',
	'nj-dropdown-bottom-sheet-title-font-size': 'text-body',
	'nj-dropdown-bottom-sheet-title-font-color': 'text-gray-900',
	'nj-dropdown-bottom-sheet-header-horizontal-padding': 'px-4',
	'nj-dropdown-bottom-sheet-header-bottom-padding': 'pb-5',
	'nj-dropdown-bottom-sheet-modal-container-padding': 'p-2',
	'nj-disclosure-container-border-width': 'border-0',
	'nj-disclosure-container-border-color': 'border-transparent',
	'nj-disclosure-container-border-radius': 'rounded-none',
	'nj-disclosure-container-padding': 'p-0',
	'nj-disclosure-container-bg-color': 'bg-white',
	'nj-disclosure-items-container-horizontal-padding': 'px-0',
	'nj-disclosure-items-container-vertical-padding': 'py-5',
	'nj-disclosure-collapsible-title-font': 'font-main-bold',
	'nj-disclosure-collapsible-title-font-size': 'text-title',
	'nj-disclosure-collapsible-title-line-height': 'leading-relaxed',
	'nj-disclosure-collapsible-title-color': 'text-gray-800',
	'nj-disclosure-collapsible-item-padding': 'p-0',
	'nj-disclosure-content-container-padding': 'p-0 pt-4',
	'nj-disclosure-expand-icon-color': 'text-gray-700',
	'nj-disclosure-dropdown-icon-color': 'text-gray-700',
	'nj-disclosure-separator-width': 'w-full',
	'nj-disclosure-separator-vertical-margin': 'my-0',
	'nj-calendar-header-text': 'text-brand-600',
	'nj-calendar-day-text': 'text-gray-900 text-paragraph',
	'nj-calendar-day-name-text': 'font-main-regular leading-6',
	'nj-calendar-month-text': 'font-main-regular text-paragraph',
	'nj-calendar-today-bg': 'bg-brand-50',
	'nj-calendar-today-text': 'text-gray-900',
	'nj-calendar-start-day': 'bg-brand-500',
	'nj-calendar-end-day': 'bg-white border-brand-500 border',
	'nj-calendar-end-day-text': 'text-brand-600',
};
