const sidebars = {
	codingStandardsSidebar: [{ type: 'autogenerated', dirName: 'coding-standards' }],
	devkitPackagesSidebar: [{ type: 'autogenerated', dirName: 'devkit-docs' }],
};

export default sidebars;
