type ValueType<T> = Record<string, T>;

export const gridSampleData = <T>({ sortable, formatted }: { sortable: boolean; formatted: boolean; }) => ({
	onFetchData: async () => fetchGridSampleData,
	columns: [
		{
			name: 'ID',
			field: 'id',
			sortable,
			frozen: 'left',
		},
		{ field: 'name', name: 'Name', sortable, width: '250px' },
		{
			field: 'weight',
			name: 'Person Weight',
			sortable,
			format: formatted ? (val: ValueType<number>) => val.weight?.toFixed(2) : undefined,
		},
		{
			name: 'Custom Field',
			format: (val: ValueType<number>) => `${val.name}'s weight is ${val.weight?.toFixed(2)}`,
			sortable,
			width: '200px',
			frozen: 'right',
		},
	] as T,
});

export const fetchGridSampleData = [
	{
		id: 0,
		name: 'John Doe',
		weight: 70,
		email: 'john.doe@example.com',
		phone: '+1-555-0101',
		status: 'Active',
		department: 'Engineering',
		salary: 75000,
		joinDate: '2023-01-15',
		isActive: true,
	},
	{
		id: 1,
		name: 'Jane Smith',
		weight: 65,
		email: 'jane.smith@example.com',
		phone: '+1-555-0102',
		status: 'Active',
		department: 'Marketing',
		salary: 68000,
		joinDate: '2023-02-20',
		isActive: true,
	},
	{
		id: 2,
		name: 'Bob Johnson',
		weight: 80,
		email: 'bob.johnson@example.com',
		phone: '+1-555-0103',
		status: 'Inactive',
		department: 'Sales',
		salary: 72000,
		joinDate: '2022-11-10',
		isActive: false,
	},
	{
		id: 3,
		name: 'Alice Brown',
		weight: 55,
		email: 'alice.brown@example.com',
		phone: '+1-555-0104',
		status: 'Active',
		department: 'HR',
		salary: 65000,
		joinDate: '2023-03-05',
		isActive: true,
	},
	{
		id: 4,
		name: 'Charlie Wilson',
		weight: 75,
		email: 'charlie.wilson@example.com',
		phone: '+1-555-0105',
		status: 'Active',
		department: 'Engineering',
		salary: 82000,
		joinDate: '2022-09-15',
		isActive: true,
	},
	{
		id: 5,
		name: 'Diana Davis',
		weight: 60,
		email: 'diana.davis@example.com',
		phone: '+1-555-0106',
		status: 'Active',
		department: 'Finance',
		salary: 70000,
		joinDate: '2023-04-12',
		isActive: true,
	},
	{
		id: 6,
		name: 'Edward Miller',
		weight: 85,
		email: 'edward.miller@example.com',
		phone: '+1-555-0107',
		status: 'Inactive',
		department: 'Operations',
		salary: 78000,
		joinDate: '2022-12-03',
		isActive: false,
	},
	{
		id: 7,
		name: 'Fiona Garcia',
		weight: 58,
		email: 'fiona.garcia@example.com',
		phone: '+1-555-0108',
		status: 'Active',
		department: 'Design',
		salary: 72000,
		joinDate: '2023-05-18',
		isActive: true,
	},
	{
		id: 8,
		name: 'George Martinez',
		weight: 72,
		email: 'george.martinez@example.com',
		phone: '+1-555-0109',
		status: 'Active',
		department: 'Engineering',
		salary: 85000,
		joinDate: '2022-08-22',
		isActive: true,
	},
	{
		id: 9,
		name: 'Helen Taylor',
		weight: 63,
		email: 'helen.taylor@example.com',
		phone: '+1-555-0110',
		status: 'Active',
		department: 'Marketing',
		salary: 69000,
		joinDate: '2023-06-30',
		isActive: true,
	},
	{
		id: 10,
		name: 'Ian Anderson',
		weight: 78,
		email: 'ian.anderson@example.com',
		phone: '+1-555-0111',
		status: 'Inactive',
		department: 'Sales',
		salary: 75000,
		joinDate: '2022-10-14',
		isActive: false,
	},
	{
		id: 11,
		name: 'Julia Thomas',
		weight: 56,
		email: 'julia.thomas@example.com',
		phone: '+1-555-0112',
		status: 'Active',
		department: 'HR',
		salary: 67000,
		joinDate: '2023-07-08',
		isActive: true,
	},
	{
		id: 12,
		name: 'Kevin Jackson',
		weight: 82,
		email: 'kevin.jackson@example.com',
		phone: '+1-555-0113',
		status: 'Active',
		department: 'Engineering',
		salary: 88000,
		joinDate: '2022-07-25',
		isActive: true,
	},
	{
		id: 13,
		name: 'Laura White',
		weight: 59,
		email: 'laura.white@example.com',
		phone: '+1-555-0114',
		status: 'Active',
		department: 'Finance',
		salary: 71000,
		joinDate: '2023-08-15',
		isActive: true,
	},
	{
		id: 14,
		name: 'Michael Harris',
		weight: 76,
		email: 'michael.harris@example.com',
		phone: '+1-555-0115',
		status: 'Inactive',
		department: 'Operations',
		salary: 79000,
		joinDate: '2022-06-12',
		isActive: false,
	},
	{
		id: 15,
		name: 'Nancy Clark',
		weight: 61,
		email: 'nancy.clark@example.com',
		phone: '+1-555-0116',
		status: 'Active',
		department: 'Design',
		salary: 73000,
		joinDate: '2023-09-20',
		isActive: true,
	},
	{
		id: 16,
		name: 'Oliver Lewis',
		weight: 79,
		email: 'oliver.lewis@example.com',
		phone: '+1-555-0117',
		status: 'Active',
		department: 'Engineering',
		salary: 86000,
		joinDate: '2022-05-18',
		isActive: true,
	},
	{
		id: 17,
		name: 'Patricia Hall',
		weight: 57,
		email: 'patricia.hall@example.com',
		phone: '+1-555-0118',
		status: 'Active',
		department: 'Marketing',
		salary: 68000,
		joinDate: '2023-10-05',
		isActive: true,
	},
	{
		id: 18,
		name: 'Quentin Young',
		weight: 81,
		email: 'quentin.young@example.com',
		phone: '+1-555-0119',
		status: 'Inactive',
		department: 'Sales',
		salary: 77000,
		joinDate: '2022-04-30',
		isActive: false,
	},
	{
		id: 19,
		name: 'Rachel King',
		weight: 64,
		email: 'rachel.king@example.com',
		phone: '+1-555-0120',
		status: 'Active',
		department: 'HR',
		salary: 69000,
		joinDate: '2023-11-12',
		isActive: true,
	},
	{
		id: 20,
		name: 'Samuel Wright',
		weight: 77,
		email: 'samuel.wright@example.com',
		phone: '+1-555-0121',
		status: 'Active',
		department: 'Engineering',
		salary: 87000,
		joinDate: '2022-03-15',
		isActive: true,
	},
];
