export const optionsGroups = [
	{
		id: 1,
		productId: 2,
		name: 'Reports',
		displayName: 'Reports',
		// parentScreenId: 9,
		sortOrder: 1000,
		isActive: true,
	},
	{
		id: 2,
		productId: 2,
		name: 'UnreviewedPoliciesReport',
		displayName: 'Report - Unreviewed Policies',
		parentScreenId: 1,
		sortOrder: 1010,
		isActive: true,
	},
	{
		id: 3,
		productId: 2,
		name: 'UnreviewedPoliciesTab',
		displayName: 'Unreviewed Policies',
		parentScreenId: 2,
		sortOrder: 1020,
		isActive: true,
	},
	{
		id: 4,
		productId: 2,
		name: 'ReviewedPoliciesTab',
		displayName: 'Reviewed Policies',
		parentScreenId: 2,
		sortOrder: 1030,
		isActive: true,
	},
	{
		id: 5,
		productId: 3,
		name: 'AgentApp',
		displayName: 'Agent App',
		parentScreenId: 2,
		sortOrder: 2000,
		isActive: true,
	},
	{
		id: 7,
		productId: 5,
		name: 'APIConsumer',
		displayName: 'API Consumer',
		// parentScreenId: 9,
		sortOrder: 1000,
		isActive: true,
	},
	// {
	// 	id: 9,
	// 	productId: 1,
	// 	name: 'All',
	// 	displayName: 'All',
	// 	parentScreenId: 0,
	// 	sortOrder: 0,
	// 	isActive: true,
	// },
	{
		id: 10,
		productId: 1,
		name: 'UserManagement',
		displayName: 'User Management',
		// parentScreenId: 9,
		sortOrder: 100,
		isActive: true,
	},
	{
		id: 11,
		productId: 1,
		name: 'RolesAndPermissions',
		displayName: 'Roles and Permissions',
		parentScreenId: 10,
		sortOrder: 150,
		isActive: true,
	},
	{
		id: 13,
		productId: 1,
		name: 'SearchUser',
		displayName: 'Search User',
		parentScreenId: 10,
		sortOrder: 200,
		isActive: true,
	},
];

export const checkboxOptions = [
	{
		id: 1,
		actionName: 'View',
		displayName: 'View',
		screenId: 2,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 2,
		actionName: 'Export',
		displayName: 'Export',
		screenId: 3,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 3,
		actionName: 'View Policy Details',
		displayName: 'View Policy Details',
		screenId: 3,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 4,
		actionName: 'Edit Vehicle Details',
		displayName: 'Edit Vehicle Details',
		screenId: 3,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 5,
		actionName: 'Export',
		displayName: 'Export',
		screenId: 4,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 6,
		actionName: 'View Policy Details',
		displayName: 'View Policy Details',
		screenId: 4,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 7,
		actionName: 'Edit Vehicle Details',
		displayName: 'Edit Vehicle Details',
		screenId: 4,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 8,
		actionName: 'Mark as Unreviewed',
		displayName: 'Mark as Unreviewed',
		screenId: 4,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 9,
		actionName: 'Sync Policy',
		displayName: 'Sync Policy',
		screenId: 5,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 10,
		actionName: 'IssuePolicy',
		displayName: 'IssuePolicy',
		screenId: 7,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 11,
		actionName: 'View',
		displayName: 'View',
		screenId: 11,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 12,
		actionName: 'AddRole',
		displayName: 'Add Role',
		screenId: 11,
		parentActionId: 11,
		isActive: true,
	},
	{
		id: 13,
		actionName: 'EditRole',
		displayName: 'Edit Role',
		screenId: 11,
		parentActionId: 11,
		isActive: true,
	},
	{
		id: 14,
		actionName: 'View',
		displayName: 'View',
		screenId: 13,
		parentActionId: 0,
		isActive: true,
	},
	{
		id: 15,
		actionName: 'AddUser',
		displayName: 'Add User',
		screenId: 13,
		parentActionId: 14,
		isActive: true,
	},
	{
		id: 16,
		actionName: 'EditUser',
		displayName: 'Edit User',
		screenId: 13,
		parentActionId: 15,
		isActive: true,
	},
	{
		id: 17,
		actionName: 'SendInvitationEmail',
		displayName: 'Send Invitation Email',
		screenId: 13,
		parentActionId: 16,
		isActive: true,
	},
	{
		id: 18,
		actionName: 'ResetUserPassword',
		displayName: 'Reset User Password',
		screenId: 13,
		parentActionId: 16,
		isActive: true,
	},
	{
		id: 19,
		actionName: 'ActivateUser',
		displayName: 'Activate User',
		screenId: 13,
		parentActionId: 14,
		isActive: true,
	},
	{
		id: 20,
		actionName: 'SuspendUser',
		displayName: 'Suspend User',
		screenId: 13,
		parentActionId: 14,
		isActive: true,
	},
	{
		id: 21,
		actionName: 'UserDetails',
		displayName: 'User Details and Activities',
		screenId: 13,
		parentActionId: 14,
		isActive: true,
	},
];
