export const globalUtils: Record<string, string> = {
	'nj-primary-button-bg': 'bg-brand-800',
	'nj-bg-brand': 'bg-brand-800',
	'nj-border-brand': 'border-brand-800',
	'nj-bg-brand-pressed': 'bg-brand-700',
	'nj-border-brand-pressed': 'border-brand-700',
	'nj-radio-button-selected': 'border-brand-500',
	'nj-radio-button': 'border-gray-500',
	'nj-radio-content': 'gap-2',
	'nj-radio-card-item-container-font-family': 'font-main-bold',
	'nj-radio-label-font-family': 'font-medium',
	'nj-radio-label-font-size': 'text-paragraph',
	'nj-radio-label-horizontal-padding': 'px-2',
	'nj-radio-icon': 'w-6 h-6',
	'nj-otp-container': 'gap-2',
	'nj-otp-input-wrapper': 'w-14 h-14 justify-center items-center',
	'nj-otp-input': 'text-body text-gray-700',
	'nj-otp-input-disabled': 'bg-gray-500',
	'nj-otp-input-disabled-text-color': 'text-gray-700',
	'nj-border-radius': 'rounded-md',
	'nj-bg-secondary': 'bg-white',
	'nj-border-secondary': 'border-brand-800',
	'nj-border-secondary-pressed': 'border-brand-700',
	'nj-social-button-border-radius': 'rounded-md',
	'nj-social-button-border': 'border-black',
	'nj-social-button-text': 'text-black',
	'nj-primary-button-text': 'text-white',
	'nj-button-spinner-bg-primary': 'bg-brand-700',
	'nj-button-spinner-bg-secondary': 'bg-white',
	'nj-text-brand': 'transparent',
	'nj-text-input-font-size': 'text-body',
	'nj-text-input-font-color': 'text-gray-600',
	'nj-text-input-line-height': 'leading-tight',
	'nj-text-input-container-padding': 'py-0.25 px-2.25',
	'nj-text-input-container-padding-small': 'py-0.25 px-2.25',
	'nj-text-input-container-padding-large': 'py-0.25 px-2.25',
	'nj-text-input-container-border-radius': 'rounded-md',
	'nj-text-input-container-error-bg': 'bg-red-100',
	'nj-text-input-container-error-border-color': 'border-red-500',
	'nj-text-input-container-disabled-border': 'border',
	'nj-text-input-container-disabled-border-color': 'border-gray-600',
	'nj-text-input-container-disabled-bg': 'bg-gray-50',
	'nj-text-input-container-bg': 'bg-white',
	'nj-text-input-container-search-bg': 'bg-white',
	'nj-text-input-container-search-border-width': 'border',
	'nj-text-area-container-height': 'h-32',
	'nj-text-area-container-bg': 'bg-white',
	'nj-text-area-container-padding': 'py-0.25 px-2.25',
	'nj-text-area-container-border-radius': 'rounded-md',
	'nj-text-area-container-border-width': 'border',
	'nj-text-area-container-border-color': 'border-gray-600',
	'nj-text-area-container-error-bg': 'bg-red-100',
	'nj-text-area-font': 'font-main-regular',
	'nj-text-area-line-height': 'leading-tight',
	'nj-text-area-letter-spacing': 'tracking-normal',
	'nj-text-area-align-items': 'items-center',
	'nj-toast-success-bg-color': 'bg-green-50',
	'nj-toast-success-text-color': 'text-green-500',
	'nj-toast-warning-bg-color': 'bg-yellow-50',
	'nj-toast-warning-text-color': 'text-yellow-500',
	'nj-toast-error-bg-color': 'bg-red-50',
	'nj-toast-error-text-color': 'text-red-500',
	'nj-toast-info-bg-color': 'bg-blue-50',
	'nj-toast-info-text-color': 'text-blue-500',
	'nj-error-text-font': 'font-medium',
	'nj-error-text-font-color': 'text-red-500',
	'nj-error-text-font-size': 'text-sm',
	'nj-text-input-prefix-default-color': 'text-gray-900',
	'nj-text-input-prefix-align-items': 'items-center',
	'nj-error-icon-display': 'hidden',
	'nj-error-container-width': 'w-full',
	'nj-error-container-bg': 'bg-transparent',
	'nj-error-container-border-radius': 'rounded-none',
	'nj-error-container-padding-horizontal': 'px-0',
	'nj-error-container-padding-vertical': 'py-0',
	'nj-error-container-margin-top': 'mt-0',
	'nj-error-container-gap': 'gap-0',
	'nj-error-container-flex': 'flex-none',
	'nj-error-container-align-items': 'items-start',
	'nj-text-field-placeholder-color': 'text-gray-500',
	'nj-otp-cell-border-size': 'border',
	'nj-otp-cell-border-color': 'border-gray-300',
	'nj-otp-positive-cell-border-color': 'border-green-500',
	'nj-alert-container-border': 'border',
	'nj-alert-container-vertical-padding': 'py-2',
	'nj-alert-container-horizontal-padding': 'px-2',
	'nj-alert-severity-icon-height': 'h-5',
	'nj-alert-severity-icon-width': 'w-5',
	'nj-alert-severity-icon-color': 'text-red-500',
	'nj-alert-close-icon-height': 'h-5',
	'nj-alert-close-icon-width': 'w-5',
	'nj-alert-bg': 'bg-red-50',
	'nj-dropdown-container-bg': 'bg-white',
	'nj-dropdown-menu-label-text-font': 'font-main-bold',
	'nj-dropdown-menu-label-text-color': 'text-gray-900',
	'nj-dropdown-menu-label-text-size': 'text-h2',
	'nj-dropdown-menu-label-height': 'h-8',
	'nj-dropdown-menu-icon-color': 'text-black',
	'nj-dropdown-menu-container-gap': 'gap-2',
	'nj-dropdown-bottom-sheet-title-font': 'font-main-bold',
	'nj-dropdown-bottom-sheet-title-font-size': 'text-body',
	'nj-dropdown-bottom-sheet-title-font-color': 'text-gray-900',
	'nj-dropdown-bottom-sheet-header-horizontal-padding': 'px-4',
	'nj-dropdown-bottom-sheet-header-bottom-padding': 'pb-5',
	'nj-dropdown-bottom-sheet-modal-container-padding': 'p-2',
	'nj-disclosure-container-border-width': 'border',
	'nj-disclosure-container-border-color': 'border-gray-200',
	'nj-disclosure-container-border-radius': 'rounded-lg',
	'nj-disclosure-container-padding': 'p-4',
	'nj-disclosure-container-bg-color': 'bg-white',
	'nj-disclosure-items-container-horizontal-padding': 'px-0',
	'nj-disclosure-items-container-vertical-padding': 'py-0',
	'nj-disclosure-collapsible-title-font': 'font-main-bold',
	'nj-disclosure-collapsible-title-font-size': 'text-body',
	'nj-disclosure-collapsible-title-line-height': 'leading-loose',
	'nj-disclosure-collapsible-title-color': 'text-black',
	'nj-disclosure-collapsible-item-padding': 'p-0',
	'nj-disclosure-content-container-padding': 'p-0 pb-1',
	'nj-disclosure-expand-icon-color': 'text-black',
	'nj-disclosure-dropdown-icon-color': 'text-black',
	'nj-calendar-header-text': 'text-brand-600',
	'nj-calendar-day-text': 'text-gray-900 text-paragraph',
	'nj-calendar-day-name-text': 'font-regular leading-6',
	'nj-calendar-month-text': 'font-regular text-paragraph',
	'nj-calendar-today-bg': 'bg-brand-50',
	'nj-calendar-today-text': 'text-gray-900',
	'nj-calendar-start-day': 'bg-brand-800',
	'nj-calendar-end-day': 'bg-white border-brand-800 border',
	'nj-calendar-end-day-text': 'text-brand-600',
};
