trigger: none

variables:
  pnpm_config_cache: $(Pipeline.Workspace)/.pnpm-store
  node_modules_directory: $(Build.SourcesDirectory)/node_modules
  build_directory: $(Build.SourcesDirectory)/.build
  server_configs_directory: $(Build.SourcesDirectory)/.server

jobs:
  - job: Storybook_Build
    displayName: Storybook - DLS Build
    pool:
      vmImage: ubuntu-24.04 # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
    steps:
      - checkout: self
        clean: False
      - task: npmAuthenticate@0
        inputs:
          workingFile: '.npmrc'

      - task: Cache@2
        inputs:
          key: 'pnpm | "$(Agent.OS)" | pnpm-lock.yaml'
          path: $(node_modules_directory)
          displayName: Cache pnpm

      - script: |
          npm install -g pnpm@latest-9
          pnpm config set store-dir $(pnpm_config_cache)
        displayName: 'Setup pnpm'

      - script: 'pnpm install --no-frozen-lockfile'
        displayName: 'pnpm install'
        # condition: eq(variables['CacheRestored'],False)

      - script: 'cp -r $(server_configs_directory) $(build_directory)'
        displayName: 'Copy server configs to build directory'

      - script: 'pnpm storybook:build'
        displayName: 'Website Build $(build_directory)'

      - script: 'npm install'
        displayName: 'Install Build Dependencies'
        workingDirectory: '$(build_directory)'

      - task: ArchiveFiles@2
        displayName: Archive build folder
        inputs:
          rootFolderOrFile: '$(build_directory)'
          includeRootFolder: false
          sevenZipCompression: 'normal'
          archiveFile: '$(build.artifactstagingdirectory)/$(Build.BuildId).zip'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: static-next-website'
        inputs:
          ArtifactName: static-next-website
